# Generated by Django 4.2 on 2023-07-20 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("photolith", "0004_annotation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="age",
            field=models.IntegerField(null=True, verbose_name="Age reading"),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="comment",
            field=models.TextField(default="", verbose_name="Comments"),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Last modified"),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="rating",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Unreadable"), (50, "Average"), (100, "Perfect")],
                null=True,
                verbose_name="Image rating",
            ),
        ),
    ]
