# Generated by Django 4.2 on 2023-08-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photolith", "0006_rename_bisect_poly_annotation_axis_poly"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="rating",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Unreadable"),
                    (50, "Difficult (+/- one year)"),
                    (100, "Easy to read"),
                ],
                null=True,
                verbose_name="Image rating",
            ),
        ),
    ]
