# Generated by Django 4.2 on 2023-08-29 14:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("photolith", "0007_alter_annotation_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=4096, verbose_name="Project name"),
                ),
                (
                    "search_qs",
                    models.CharField(
                        max_length=4096, verbose_name="Search querystring"
                    ),
                ),
                (
                    "date_end",
                    models.DateField(
                        default=datetime.date(2023, 9, 26),
                        verbose_name="Project end date",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last modified"),
                ),
                (
                    "base_user",
                    models.ForeignKey(
                        help_text="If a user is selected, then their most recent annotation for each individual will be used as a starting point for annotations",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects_based_on_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Base axis on user",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
            ],
        ),
    ]
