# Generated by Django 4.2 on 2023-08-29 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("photolith", "0008_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="photolith.project",
                verbose_name="Part of project",
            ),
        ),
    ]
