# Generated by Django 4.2 on 2023-08-30 16:15

from django.db import migrations, models
import photolith.models


class Migration(migrations.Migration):
    dependencies = [
        ("photolith", "0009_annotation_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="date_end",
            field=models.DateField(
                default=photolith.models.in_4_weeks, verbose_name="Project end date"
            ),
        ),
    ]
