# Generated by Django 4.2 on 2023-09-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photolith", "0012_add_project_group"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="annotation",
            index=models.Index(
                fields=["individual"], name="photolith_a_individ_cbfb43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="annotation",
            index=models.Index(
                fields=["created_by", "individual"],
                name="photolith_a_created_90ae77_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="metachar",
            index=models.Index(fields=["key"], name="photolith_m_key_12c252_idx"),
        ),
        migrations.AddIndex(
            model_name="metanumeric",
            index=models.Index(fields=["key"], name="photolith_m_key_23c958_idx"),
        ),
        migrations.AddIndex(
            model_name="metatx",
            index=models.Index(
                fields=["key", "value"], name="photolith_m_key_f458b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taxonomy",
            index=models.Index(
                fields=["key", "identifier"], name="photolith_t_key_c8fc6c_idx"
            ),
        ),
    ]
