# Generated by Django 4.2 on 2023-09-08 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("photolith", "0013_annotation_photolith_a_individ_cbfb43_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="individual",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="individual",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Modified at"),
        ),
    ]
