# Generated by Django 4.2 on 2023-09-08 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("photolith", "0014_alter_individual_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaDT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("value", models.DateTimeField(blank=True, null=True)),
                (
                    "individual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="photolith.individual",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="metadt",
            index=models.Index(fields=["key"], name="photolith_m_key_13f464_idx"),
        ),
    ]
