# Generated by Django 4.2 on 2023-09-11 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("photolith", "0015_metadt_metadt_photolith_m_key_13f464_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="authority",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Unknown"),
                    (50, "Human, non expert"),
                    (100, "Human, expert"),
                ],
                default=0,
                verbose_name="Reader authority",
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "species_expert",
                    models.ForeignKey(
                        limit_choices_to={"key": "species"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="photolith.taxonomy",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
