# Generated by Django 4.2 on 2023-09-18 07:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photolith", "0016_annotation_authority_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="href",
        ),
    ]
