# Generated by Django 4.2 on 2023-09-18 08:03

from django.db import migrations, models
import photolith.models


class Migration(migrations.Migration):
    dependencies = [
        ("photolith", "0017_remove_image_href"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="content",
            field=models.ImageField(
                null=True,
                storage=photolith.models.default_storage,
                upload_to="image_content",
            ),
        ),
    ]
