# Generated by Django 4.2 on 2023-10-03 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("photolith", "0019_team_project_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="search_qs",
        ),
        migrations.AddField(
            model_name="project",
            name="individuals",
            field=models.ManyToManyField(to="photolith.individual"),
        ),
        migrations.AlterField(
            model_name="project",
            name="team",
            field=models.ForeignKey(
                help_text="The set of users that should perform the annotation as part of the project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="photolith.team",
            ),
        ),
    ]
