# Generated by Django 4.2 on 2023-10-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photolith", "0020_remove_project_search_qs_project_individuals_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="species_expert",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="species_expert",
            field=models.ManyToManyField(
                limit_choices_to={"key": "species"}, to="photolith.taxonomy"
            ),
        ),
    ]
