# Generated by Django 4.2 on 2023-11-20 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("photolith", "0022_annotate_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taxonomy",
            options={"verbose_name_plural": "Taxonomies"},
        ),
        migrations.AlterField(
            model_name="annotation",
            name="authority",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Unknown"),
                    (20, "Automated reader"),
                    (50, "Non expert, from image"),
                    (55, "Non expert, with original otoliths or slides"),
                    (100, "Expert, from image"),
                    (105, "Expert, with original otoliths or slides"),
                ],
                default=0,
                verbose_name="Reader authority",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="team",
            field=models.ForeignKey(
                help_text="The set of users that should be included in the project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="photolith.team",
            ),
        ),
        migrations.AlterField(
            model_name="taxonomy",
            name="key",
            field=models.CharField(max_length=255, verbose_name="Metadata key"),
        ),
        migrations.AlterField(
            model_name="taxonomy",
            name="str_en",
            field=models.CharField(max_length=255, verbose_name="English"),
        ),
        migrations.AlterField(
            model_name="taxonomy",
            name="str_is",
            field=models.CharField(max_length=255, verbose_name="Icelandic"),
        ),
    ]
