# Generated by Django 4.2 on 2023-11-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "photolith",
            "0023_alter_taxonomy_options_alter_annotation_authority_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="taxonomy",
            constraint=models.UniqueConstraint(
                fields=("key", "identifier"), name="taxonomy_key_identifier"
            ),
        ),
    ]
