# Generated by Django 4.2 on 2024-11-21 10:16

from django.db import migrations, models
import django.db.models.deletion

from photolith.models import MetaTx, Taxonomy


def forward_f(apps, schema_editor):
    if schema_editor.connection.alias != "default":
        return

    for mtx in MetaTx.objects.all():
        if mtx.value_id is None:
            # Entry with NULL, make a dummy entry and assign items to that
            unknown_tx, created = Taxonomy.objects.get_or_create(
                key=mtx.key,
                identifier=-9,
                defaults=dict(str_en="Missing"),
            )
            mtx.value = unknown_tx
            mtx.save()


def reverse_f(apps, schema_editor):
    if schema_editor.connection.alias != "default":
        return

    for mtx in MetaTx.objects.all():
        # Allow reversal only if there's nothing to do
        if mtx.value.identifier == -9 and mtx.value.str_en == "Missing":
            raise ValueError("Cannot reverse migration, invalid data: %s" % mtx)


class Migration(migrations.Migration):
    dependencies = [
        ("photolith", "0025_alter_annotation_rating"),
    ]

    operations = [
        migrations.RunPython(forward_f, reverse_f),
        migrations.AlterField(
            model_name="metatx",
            name="value",
            field=models.ForeignKey(
                null=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="photolith.taxonomy",
            ),
        ),
        migrations.AlterField(
            model_name="taxonomy",
            name="identifier",
            field=models.IntegerField(
                help_text="A numeric identifier. Should be unique for each key, can repeat 1 for 'species' & 'sex', but cannot have 2 entries with both 1 & 'species'",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="taxonomy",
            name="key",
            field=models.CharField(
                help_text="The taxonomy this entry is added to, a lower-case identifier, e.g. 'species'",
                max_length=255,
                verbose_name="Metadata key",
            ),
        ),
    ]
