# Generated by Django 4.2 on 2024-11-28 13:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photolith", "0026_alter_metatx_value_alter_taxonomy_identifier_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="annotation",
            options={
                "verbose_name": "Annotation",
                "verbose_name_plural": "Annotations",
            },
        ),
        migrations.AlterModelOptions(
            name="image",
            options={"verbose_name": "Image", "verbose_name_plural": "Images"},
        ),
        migrations.AlterModelOptions(
            name="individual",
            options={
                "verbose_name": "Individual",
                "verbose_name_plural": "Individuals",
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "Project", "verbose_name_plural": "Projects"},
        ),
        migrations.AlterModelOptions(
            name="taxonomy",
            options={"verbose_name": "Taxonomy", "verbose_name_plural": "Taxonomies"},
        ),
        migrations.AlterModelOptions(
            name="team",
            options={"verbose_name": "Team", "verbose_name_plural": "Teams"},
        ),
    ]
