# Generated by Django 4.2 on 2024-11-28 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forward_f(apps, schema_editor):
    if schema_editor.connection.alias != "default":
        return

    User = apps.get_model("auth", "User")
    UserSpeciesAuthority = apps.get_model("photolith", "UserSpeciesAuthority")
    for u in User.objects.all():
        if not hasattr(u, "userprofile"):
            continue
        for species in u.userprofile.species_expert.all():
            UserSpeciesAuthority.objects.create(
                user=u,
                species=species,
                level=100,
            )


def reverse_f(apps, schema_editor):
    if schema_editor.connection.alias != "default":
        return


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("photolith", "0027_alter_annotation_options_alter_image_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="base_authority_level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (20, "Automated reader"),
                    (50, "Inexperienced"),
                    (80, "Junior"),
                    (100, "Expert"),
                    (120, "Senior expert"),
                ],
                default=50,
                verbose_name="Reader authority",
            ),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="authority",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (20, "Automated reader, from image"),
                    (25, "Automated reader, with original otoliths or slides"),
                    (50, "Inexperienced, from image"),
                    (55, "Inexperienced, with original otoliths or slides"),
                    (80, "Junior, from image"),
                    (85, "Junior, with original otoliths or slides"),
                    (100, "Expert, from image"),
                    (105, "Expert, with original otoliths or slides"),
                    (120, "Senior expert, from image"),
                    (125, "Senior expert, with original otoliths or slides"),
                ],
                default=50,
                verbose_name="Reader authority",
            ),
        ),
        migrations.CreateModel(
            name="UserSpeciesAuthority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (20, "Automated reader"),
                            (50, "Inexperienced"),
                            (80, "Junior"),
                            (100, "Expert"),
                            (120, "Senior expert"),
                        ],
                        default=50,
                        verbose_name="Reader authority",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        limit_choices_to={"key": "species"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="photolith.taxonomy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "species")},
            },
        ),
        migrations.RunPython(forward_f, reverse_f),
        migrations.RemoveField(
            model_name="userprofile",
            name="species_expert",
        ),
    ]
