# Generated by Django 4.2 on 2026-04-10 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("photolith", "0028_remove_userprofile_species_expert_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userspeciesauthority",
            options={
                "verbose_name": "User species authority",
                "verbose_name_plural": "User species authorities",
            },
        ),
        migrations.AlterField(
            model_name="annotation",
            name="rating",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "3"), (50, "2"), (100, "1")],
                null=True,
                verbose_name="Image rating",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="base_user",
            field=models.ForeignKey(
                help_text="If a user is selected, then their most recent annotation for each individual will be used as an axis starting point for annotations",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects_based_on_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Base axis on user",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="base_authority_level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (20, "Automated reader"),
                    (50, "Inexperienced"),
                    (80, "Junior"),
                    (100, "Expert"),
                    (120, "Senior expert"),
                ],
                default=50,
                help_text="The reader's authority level (annotations from more expert readers will be considered before others). Used when a species authority doesn't apply",
                verbose_name="Reader annotation authority",
            ),
        ),
        migrations.AlterField(
            model_name="userspeciesauthority",
            name="level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (20, "Automated reader"),
                    (50, "Inexperienced"),
                    (80, "Junior"),
                    (100, "Expert"),
                    (120, "Senior expert"),
                ],
                default=50,
                help_text="The authority level (annotations from more expert readers will be considered before others)",
                verbose_name="Reader annotation authority",
            ),
        ),
        migrations.AlterField(
            model_name="userspeciesauthority",
            name="species",
            field=models.ForeignKey(
                help_text="The species for which the user is more expert in",
                limit_choices_to={"key": "species"},
                on_delete=django.db.models.deletion.CASCADE,
                to="photolith.taxonomy",
            ),
        ),
    ]
