# Generated by Django 4.2 on 2026-04-09 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("photolith", "0029_alter_userspeciesauthority_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="rating",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "3"), (50, "2"), (100, "1")],
                null=True,
                verbose_name="Image rating",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="base_user",
            field=models.ForeignKey(
                help_text="If a user is selected, then their most recent annotation for each individual will be used as an axis starting point for annotations",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects_based_on_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Base axis on user",
            ),
        ),
    ]
