# Generated by Django 5.2.13 on 2026-04-29 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photolith", "0030_remove_meta_duplicates"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaInteger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("value", models.IntegerField(blank=True, null=True)),
                (
                    "individual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="photolith.individual",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["key"], name="photolith_m_key_599b90_idx")
                ],
            },
        ),
    ]
