# Generated by Django 5.2.13 on 2026-05-07 10:56

import django.db.models.deletion
import photolith.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photolith", "0033_migrate_station_year_month_to_metainteger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="annotation",
            options={
                "verbose_name": "annotation",
                "verbose_name_plural": "annotations",
            },
        ),
        migrations.AlterModelOptions(
            name="image",
            options={"verbose_name": "image", "verbose_name_plural": "images"},
        ),
        migrations.AlterModelOptions(
            name="individual",
            options={
                "verbose_name": "individual",
                "verbose_name_plural": "individuals",
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "project", "verbose_name_plural": "projects"},
        ),
        migrations.AlterModelOptions(
            name="taxonomy",
            options={"verbose_name": "taxonomy", "verbose_name_plural": "taxonomies"},
        ),
        migrations.AlterModelOptions(
            name="team",
            options={"verbose_name": "team", "verbose_name_plural": "teams"},
        ),
        migrations.AlterModelOptions(
            name="userspeciesauthority",
            options={
                "verbose_name": "user species authority",
                "verbose_name_plural": "user species authorities",
            },
        ),
        migrations.AlterField(
            model_name="annotation",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="photolith.project",
                verbose_name="part of project",
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="base_user",
            field=models.ForeignKey(
                help_text="If a user is selected, then their most recent annotation for each individual will be used as an axis starting point for annotations",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects_based_on_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="base axis on user",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="date_end",
            field=models.DateField(
                default=photolith.models.in_4_weeks, verbose_name="project end date"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=4096, verbose_name="project name"),
        ),
        migrations.AlterField(
            model_name="taxonomy",
            name="key",
            field=models.CharField(
                help_text="The taxonomy this entry is added to, a lower-case identifier, e.g. 'species'",
                max_length=255,
                verbose_name="metadata key",
            ),
        ),
        migrations.AlterField(
            model_name="taxonomy",
            name="str_en",
            field=models.CharField(max_length=255, verbose_name="english"),
        ),
        migrations.AlterField(
            model_name="taxonomy",
            name="str_is",
            field=models.CharField(max_length=255, verbose_name="icelandic"),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=4096, verbose_name="team name"),
        ),
        migrations.AlterField(
            model_name="team",
            name="users",
            field=models.ManyToManyField(
                to=settings.AUTH_USER_MODEL, verbose_name="team members"
            ),
        ),
    ]
