#!/bin/sh
set -eu
DEFAULT_HOST="$(printf ${APP_ALLOWED_HOSTS} | cut -d" " -f1)"
EXTRA_HOSTS="$(printf ${APP_ALLOWED_HOSTS} | cut -d" " -f2-)"
CERT_DIR="/var/lib/dehydrated/certs"
INGEST_ROOT="/srv/app/ingest_root"
# NB: Without .db because pam_userdb.so magically adds it on the end
INGEST_USERDB="${INGEST_ROOT}/vsftpd"

# References:
# * https://www.cyberciti.biz/tips/centos-redhat-vsftpd-ftp-with-virtual-users.html
# * https://serverfault.com/questions/931127/ftp-pam-setup-for-vsftpd
# * https://github.com/fauria/docker-vsftpd/blob/master/run-vsftpd.sh

# Create an initial user database
if [ ! -e "${INGEST_USERDB}.db" ]; then
  db_load -T -t hash -f /dev/null "${INGEST_USERDB}.db"
  chmod 600 -- "${INGEST_USERDB}.db"
fi

# db_load -T -t hash -f vusers.txt vsftpd-virtual-user.db
# chmod 600 vsftpd-virtual-user.db
# rm vusers.txt

# FTP configuration
cat <<EOF > /etc/vsftpd.conf
# Generated by https://github.com/photolith/photolith

# Activate virtual users
guest_enable=YES
virtual_use_local_privs=YES
write_enable=YES

# Force user into their own directory
user_sub_token=\$USER
local_root=${INGEST_ROOT}/\$USER
chroot_local_user=YES
allow_writeable_chroot=YES
hide_ids=YES

# PASV ports should match with docker/compose.yml
pasv_min_port=21100
pasv_max_port=21110

# Make uploads readable by others (i.e. by uwsgi)
file_open_mode=0666
local_umask=0022

# This string is the name of the PAM service vsftpd will use.
pam_service_name=vsftpd

# This option specifies the location of the RSA certificate to use for SSL
# encrypted connections.
rsa_cert_file=${CERT_DIR}/${DEFAULT_HOST}/fullchain.pem
rsa_private_key_file=${CERT_DIR}/${DEFAULT_HOST}/privkey.pem
ssl_enable=YES
force_local_logins_ssl=NO
force_local_data_ssl=NO

background=NO
listen=YES
listen_address=0.0.0.0
listen_ipv6=NO

anonymous_enable=NO
allow_anon_ssl=NO
local_enable=YES
dirmessage_enable=NO
use_localtime=YES
xferlog_enable=YES
connect_from_port_20=YES
utf8_filesystem=YES

# This option should be the name of a directory which is empty.  Also, the
# directory should not be writable by the ftp user. This directory is used
# as a secure chroot() jail at times vsftpd does not require filesystem
# access.
secure_chroot_dir=/var/run/vsftpd/empty
EOF
mkdir -p -- /var/run/vsftpd/empty
chown root:root /var/run/vsftpd/empty

cat <<EOF > /etc/pam.d/vsftpd
#%PAM-1.0
auth       required     pam_userdb.so db=${INGEST_USERDB} crypt=none
account    required     pam_userdb.so db=${INGEST_USERDB}
EOF

cleanup() {
  if [ -n "${PID_DAEMON-}" ]; then
    kill -TERM "${PID_DAEMON}"
    PID_DAEMON=""
  fi
  exit 0
}
trap cleanup TERM

vsftpd /etc/vsftpd.conf &
PID_DAEMON="$!"

while [ -n "${PID_DAEMON}" ]; do
    # NB: Signals will wait until sleep is finished if sleep is in foreground:
    #     https://mywiki.wooledge.org/SignalTrap#When_is_the_signal_handled.3F
    sleep 60 &
    wait $!

    find "${INGEST_ROOT}"/* -type f -ctime +1 -exec rm -- {} \;
done
