#!/bin/sh
set -eu
PROJECT_PATH="${PROJECT_PATH-$(dirname "$(readlink -f "$0")")}"  # The full project path
PROJECT_NAME="${PROJECT_NAME-$(basename ${PROJECT_PATH})}"  # The project directory name
DEFAULT_HOST="$(${PROJECT_PATH}/manage.py config_param --head ALLOWED_HOSTS)"
EXTRA_HOSTS="$(${PROJECT_PATH}/manage.py config_param --tail ALLOWED_HOSTS)"
CERT_DIR="/var/lib/dehydrated/certs"
DOMAINS_DIR="/etc/dehydrated/domains.txt.d"
DHPARAM="/etc/ssl/dhparam.pem"

# Install dependencies
apt install -y nginx dehydrated

# Add hosts to dehydrated config
mkdir -p "${DOMAINS_DIR}"
echo "${DEFAULT_HOST} ${EXTRA_HOSTS}" > "${DOMAINS_DIR}/${PROJECT_NAME}.txt"

# Self-signed bootstrap-cert
mkdir -p "${CERT_DIR}/${DEFAULT_HOST}"
if [ ! -e "${CERT_DIR}/${DEFAULT_HOST}/privkey.pem" ]; then
    openssl req -x509 -newkey rsa:4096 -sha256 -days 365 -nodes \
            -keyout "${CERT_DIR}/${DEFAULT_HOST}/privkey-ss.pem" \
            -out "${CERT_DIR}/${DEFAULT_HOST}/fullchain-ss.pem" \
            -subj "/CN=${DEFAULT_HOST}" \
            -addext "subjectAltName = DNS:selfsigned.${DEFAULT_HOST}"
    ln -rs ${CERT_DIR}/${DEFAULT_HOST}/privkey-ss.pem ${CERT_DIR}/${DEFAULT_HOST}/privkey.pem
    ln -rs ${CERT_DIR}/${DEFAULT_HOST}/fullchain-ss.pem ${CERT_DIR}/${DEFAULT_HOST}/fullchain.pem
    ln -rs ${CERT_DIR}/${DEFAULT_HOST}/fullchain-ss.pem ${CERT_DIR}/${DEFAULT_HOST}/chain.pem
fi

# Generate dhparam
[ -e "${DHPARAM}" ] || openssl dhparam -out "${DHPARAM}" 4096

# Create NGINX config
cat <<EOF > /etc/nginx/sites-available/${PROJECT_NAME}
upstream gunicorn {
  server 127.0.0.1:8000 fail_timeout=0;
}

server {
    listen 80;
    listen [::]:80;
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name ${DEFAULT_HOST} ${EXTRA_HOSTS};
    location /.well-known/acme-challenge {
        alias /var/lib/dehydrated/acme-challenges;
    }
    if (\$scheme != "https") {
        return 301 https://\$server_name\$request_uri;
    }

    ssl_certificate      ${CERT_DIR}/${DEFAULT_HOST}/fullchain.pem;
    ssl_certificate_key  ${CERT_DIR}/${DEFAULT_HOST}/privkey.pem;
    ssl_trusted_certificate ${CERT_DIR}/${DEFAULT_HOST}/fullchain.pem;
    ssl_dhparam ${DHPARAM};

    # Generated by https://ssl-config.mozilla.org/
    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;  # about 40000 sessions
    ssl_session_tickets off;

    # intermediate configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305;
    ssl_prefer_server_ciphers off;

    client_max_body_size 10G;

    location = /favicon.ico {
        return 301 /static/images/favicon.ico;
    }

    location ~ ^/apple-touch-.* {
        return 301 /static/images\$request_uri;
    }

    location = /robots.txt {
        add_header Content-Type text/plain;
        return 200 'User-agent: *\nAllow: /';
    }

    location /static/ {
        alias ${PROJECT_PATH}/staticfiles/;
    }

    location /media/ {
        alias ${PROJECT_PATH}/media/;
    }

    location /doc/ {
        alias ${PROJECT_PATH}/doc/_build/html/;
    }

    location / {
        # Originating IP address
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;

        # pass the Host: header from the client right along so redirects
        # can be set properly
        proxy_set_header Host \$http_host;

        # See settings.py:SECURE_PROXY_SSL_HEADER - tell Django the HTTP scheme
        # so CSRF-checks can do is_secure() + Host = HTTP_ORIGIN in _origin_verified()
        proxy_set_header X-Forwarded-Proto \$scheme;

        # we don't want nginx trying to do something clever with
        # redirects, we set the Host: header above already.
        proxy_redirect off;

        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$http_connection;

        # Try to serve static files from nginx, no point in making app serve static files.
        if (!-f \$request_filename) {
            proxy_pass http://gunicorn;
            break;
        }
    }
}
EOF
ln -rsf /etc/nginx/sites-available/${PROJECT_NAME} /etc/nginx/sites-enabled/${PROJECT_NAME}
nginx -t
/etc/init.d/nginx reload
