#!/bin/sh
set -eux
PROJECT_PATH="${PROJECT_PATH-$(dirname "$(readlink -f "$0")")}"  # The full project path
PROJECT_NAME="${PROJECT_NAME-$(basename ${PROJECT_PATH})}"  # The project directory name
DEFAULT_HOST="$(${PROJECT_PATH}/manage.py config_param --head ALLOWED_HOSTS)"
EXTRA_HOSTS="$(${PROJECT_PATH}/manage.py config_param --tail ALLOWED_HOSTS)"
CERT_DIR="/var/lib/dehydrated/certs"
DOMAINS_DIR="/etc/dehydrated/domains.txt.d"
DHPARAM="/etc/ssl/dhparam.pem"
INGEST_ROOT="$(${PROJECT_PATH}/manage.py config_param --head INGEST_ROOT)"
# NB: Without .db because pam_userdb.so magically adds it on the end
INGEST_USERDB="${INGEST_ROOT}/vsftpd"

# Install dependencies
apt-get -y install --no-install-recommends vsftpd db-util

# References:
# * https://www.cyberciti.biz/tips/centos-redhat-vsftpd-ftp-with-virtual-users.html
# * https://serverfault.com/questions/931127/ftp-pam-setup-for-vsftpd
# * https://github.com/fauria/docker-vsftpd/blob/master/run-vsftpd.sh

# Create an initial user database
if [ ! -e "${INGEST_USERDB}.db" ]; then
  db_load -T -t hash -f /dev/null "${INGEST_USERDB}.db"
  chmod 600 -- "${INGEST_USERDB}.db"
fi

# FTP configuration
cat <<EOF > /etc/vsftpd.conf
# Generated by https://github.com/photolith/photolith

# Activate virtual users
guest_enable=YES
virtual_use_local_privs=YES
write_enable=YES

# Force user into their own directory
user_sub_token=\$USER
local_root=${INGEST_ROOT}/\$USER
chroot_local_user=YES
allow_writeable_chroot=YES
hide_ids=YES

# PASV ports should match with docker/compose.yml
pasv_min_port=21100
pasv_max_port=21110

# Make uploads readable by others (i.e. by uwsgi)
file_open_mode=0666
local_umask=0022

# This string is the name of the PAM service vsftpd will use.
pam_service_name=vsftpd

# This option specifies the location of the RSA certificate to use for SSL
# encrypted connections.
rsa_cert_file=${CERT_DIR}/${DEFAULT_HOST}/fullchain.pem
rsa_private_key_file=${CERT_DIR}/${DEFAULT_HOST}/privkey.pem
ssl_enable=YES

background=NO
listen=YES
listen_address=0.0.0.0
listen_ipv6=NO

anonymous_enable=NO
allow_anon_ssl=NO
local_enable=YES
dirmessage_enable=NO
use_localtime=YES
xferlog_enable=YES
connect_from_port_20=YES
utf8_filesystem=YES

# This option should be the name of a directory which is empty.  Also, the
# directory should not be writable by the ftp user. This directory is used
# as a secure chroot() jail at times vsftpd does not require filesystem
# access.
secure_chroot_dir=/var/run/vsftpd/empty
EOF
mkdir -p -- /var/run/vsftpd/empty
chown root:root /var/run/vsftpd/empty

cat <<EOF > /etc/pam.d/vsftpd
#%PAM-1.0
auth       required     pam_userdb.so db=${INGEST_USERDB} crypt=none
account    required     pam_userdb.so db=${INGEST_USERDB}
EOF

/etc/init.d/vsftpd restart
