"""
Django settings for photolith project.

Generated by 'django-admin startproject' using Django 3.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path


try:
    from .version import GIT_REVISION
except ImportError:
    GIT_REVISION = "unknown"


BASE_DIR = Path(__file__).resolve().parent.parent


# Application definition
INSTALLED_APPS = [
    "crispy_forms",
    "crispy_bootstrap5",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "photolith",
]
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
ROOT_URLCONF = "photolith.urls"
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.i18n",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django_settings_export.settings_export",
            ],
        },
    },
]
WSGI_APPLICATION = "photolith.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR.parent / "db" / "db.sqlite3",
    }
}


# Allow Nginx to tell us what the scheme was
# so CSRF-checks can do is_secure() + Host = HTTP_ORIGIN in _origin_verified()
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Authentication
LOGIN_REDIRECT_URL = "/"


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/
from django.utils.translation import get_language_info

LANGUAGE_CODE = "en"
TIME_ZONE = "UTC"
USE_I18N = True
USE_L10N = True
USE_TZ = True
LANGUAGES = [
    (lang, get_language_info(lang)["name_translated"])
    for lang in (
        "is",
        "en-gb",
    )
]
LOCALE_PATHS = [BASE_DIR / "locale/"]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_ROOT = BASE_DIR.parent / "staticfiles"
STATIC_URL = "/static/"
STATICFILES_DIRS = (
    BASE_DIR.parent / "client/dist",
    BASE_DIR.parent / "node_modules",
)


# Default clientside settings (exported )
CS_METADATA_API = "DummyMetadataApi"
CS_METADATA_BASE = ""
CS_GIT_REVISION = GIT_REVISION
# Export anything CS_ via. django_settings_export
SETTINGS_EXPORT = [x for x in globals().keys() if x.startswith("CS_")]


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Crispy forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


# FTP upload
INGEST_ROOT = BASE_DIR.parent / "ingest_root"

# Image storage
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {},
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}
MEDIA_ROOT = BASE_DIR.parent / "media"
MEDIA_URL = "/media/"

# Logging
LOGGING = {
    "version": 1,
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {},
}

# Allow overrides via. environment (for docker)
for k in os.environ.keys():
    if k.startswith("APP_DB_"):
        DATABASES["default"][k.replace("APP_DB_", "")] = os.environ[k]
    elif k == "APP_STORAGE_BACKEND":
        STORAGES["default"]["BACKEND"] = os.environ[k]
    elif k.startswith("APP_STORAGE_"):
        STORAGES["default"]["OPTIONS"][k.replace("APP_STORAGE_", "")] = os.environ[k]
    elif k == "APP_ALLOWED_HOSTS":
        ALLOWED_HOSTS = os.environ["APP_ALLOWED_HOSTS"].split(" ")
    elif k == "APP_AUTH_PASSWORD_VALIDATORS":
        AUTH_PASSWORD_VALIDATORS = (
            os.environ[k].split(" ") if len(os.environ[k]) > 0 else []
        )
        AUTH_PASSWORD_VALIDATORS = [dict(name=x) for x in AUTH_PASSWORD_VALIDATORS]
    elif k == "APP_LOG_DB":
        LOGGING["loggers"]["django.db.backends"] = {
            "level": "DEBUG",
            "handlers": ["console"],
        }
    elif k.startswith("APP_"):
        globals()[k.replace("APP_", "")] = os.environ[k]
