"""
Django settings for photolith project.

Generated by 'django-admin startproject' using Django 3.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent


# Application definition
INSTALLED_APPS = [
    "crispy_forms",
    "crispy_bootstrap5",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "photolith",
]
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
ROOT_URLCONF = "photolith.urls"
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.i18n",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django_settings_export.settings_export",
            ],
        },
    },
]
WSGI_APPLICATION = "photolith.wsgi.application"

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR.parent / "db" / "db.sqlite3",
    }
}


# Allow Nginx to tell us what the scheme was
# so CSRF-checks can do is_secure() + Host = HTTP_ORIGIN in _origin_verified()
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Authentication
LOGIN_REDIRECT_URL = "/"


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/
from django.utils.translation import get_language_info

LANGUAGE_CODE = "en"
TIME_ZONE = "UTC"
USE_I18N = True
USE_L10N = True
USE_TZ = True
LANGUAGES = [
    (lang, get_language_info(lang)["name_translated"])
    for lang in (
        "is",
        "en",
    )
]
LOCALE_PATHS = [BASE_DIR / "locale/"]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_ROOT = BASE_DIR.parent / "staticfiles"
STATIC_URL = "/static/"
STATICFILES_DIRS = (
    BASE_DIR.parent / "client/dist",
    BASE_DIR.parent / "node_modules",
)


# Settings export (i.e. Javascript configuration)
CLIENTSIDE_CONFIG = """
window.mApi = new DummyMetadataApi();
"""
SETTINGS_EXPORT = ["CLIENTSIDE_CONFIG"]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Crispy forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


# FTP upload
INGEST_ROOT = BASE_DIR.parent / "ingest_root"

# Image storage
MEDIA_ROOT = BASE_DIR.parent / "media"


# Allow overrides via. environment (for docker)
if 'APP_DEBUG' in os.environ:
    DEBUG = os.environ['APP_DEBUG']
if 'APP_CLIENTSIDE_CONFIG' in os.environ:
    CLIENTSIDE_CONFIG = os.environ['APP_CLIENTSIDE_CONFIG']
if 'APP_ALLOWED_HOSTS' in os.environ:
    ALLOWED_HOSTS = os.environ['APP_ALLOWED_HOSTS'].split(" ")
if 'APP_SECRET_KEY' in os.environ:
    SECRET_KEY = os.environ['APP_SECRET_KEY']
