version: '3.8'

services:
  wsgi:
    build:
      context: ../
      dockerfile: docker/wsgi/Dockerfile
    volumes:
      - static:/srv/app/staticfiles
      - media:/srv/app/media
      - ingest:/srv/app/ingest_root
    expose:
      - 8000
    env_file:
      - ./.env
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static:/srv/app/staticfiles
      - media:/srv/app/media
      - certs:/var/lib/dehydrated/certs
      - db:/srv/app/db
    ports:
      - 8443:443
      - 8080:80
    env_file:
      - ./.env
    depends_on:
      - wsgi
  ftpd:
    build:
      context: ./ftpd
      dockerfile: Dockerfile
    volumes:
      - ingest:/srv/app/ingest_root
      - certs:/var/lib/dehydrated/certs
    ports:
      - 8021:021
      - 21100-21110:21100-21110
    env_file:
      - ./.env
    depends_on:
      - wsgi
      - nginx

volumes:
  certs:
  db:
  static:
  media:
  ingest:
