version: '3.8'

services:
  wsgi:
    build:
      context: ../
      dockerfile: docker/wsgi/Dockerfile
    volumes:
      - static:/srv/app/staticfiles
      - media:/srv/app/media
      - ingest:/srv/app/ingest_root
    expose:
      - 8000
    env_file:
      - ./.env

volumes:
  static:
  media:
  ingest:
